samplesheet: "config/samples.tsv"
alignment_dir: "results/umi_tools/dedup"
reference_fai: "results/get_genome/genome.fasta.fai"

filter_alignment:
  region: "KF297339.1"
  extra: "-b -f 2 -F 256 -F 2048 -F 4 -F 8 -q 30"

filter_frags:
  min_count: 10
  min_width: 30
  max_width: 60

call_tss:
  min_score: 1000

mapping_stats:
  deeptools_coverage:
    extra: "--normalizeUsing CPM --region KF297339.1 --binSize 1 --exactScaling"